name: Test Windows

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.2"]
        architecture: ["arm64"]

    timeout-minutes: 30

    name: Python ${{ matrix.python-version }} ${{ matrix.architecture }}

    steps:
    - name: Checkout action-test
      uses: actions/checkout@v3
      
    - name: Checkout type_ast
      uses: actions/checkout@v3
      with:
        repository: python/typed_ast
        path: .
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    
    - name: install arm64 python
      run: |
        env
        nuget install pythonarm64 -Version ${{ matrix.python-version }} -OutputDirectory .
        tree .\pythonarm64.${{ matrix.python-version }} /F
        ls
    
    - name: Build Package
      run: |
        python -m pip install -U pip setuptools wheel
        mkdir package_wheel
        python setup.py build_ext -L  .\pythonarm64.${{ matrix.python-version }}\tools\libs bdist_wheel -d .\package_wheel

  success:
    permissions:
      contents: none
    needs: build
    runs-on: ubuntu-latest
    name: Windows Test Successful
    steps:
      - name: Success
        run: echo Windows Test Successful
